# Generated by Django 5.1.3 on 2024-11-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_email', '0001_initial'),
        ('user_profiles', '0003_profile_mfa_email_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfaemail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile'),
        ),
    ]
