# Generated by Django 5.1.3 on 2024-11-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_email', '0004_alter_mfaemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfaemail',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
