# Generated by Django 5.1.4 on 2024-12-28 20:22

import django.core.validators
import django.db.models.deletion
import user_profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to=user_profiles.models.rename_avatar, validators=[django.core.validators.validate_image_file_extension])),
                ('language', models.CharField(choices=[('EN', 'English'), ('ZH', 'Mandarin'), ('MY', 'Malay')], default='EN', max_length=2)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('mfa_email_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
