# Generated by Django 5.1.4 on 2024-12-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
    ]
