# Generated by Django 5.1.4 on 2024-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0009_remove_profile_is_online_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ZH', 'Mandarin'), ('MY', 'Malay')], default='EN', max_length=2),
        ),
    ]
