services:

    nginx:
      build:
        context: ./requirements/nginx/.
      container_name: nginx
      ports:
        - "443:443"
        - "80:80"
      restart: on-failure
      depends_on:
        - django
      volumes:
        - vol_django:/django/
      networks:
        - net_trans

    django:
      build:
        context: ./requirements/django/.
      container_name: django
      expose:
        - "8000:8000"
      restart: on-failure
      volumes:
        - ./requirements/django/webapp/:/django/
        - vol_django:/django/
      networks:
        - net_trans
      env_file:
        - .env

    postgres:
      image: postgres:latest
      container_name: postgres
      ports:
        - "5432:5432"
      restart: on-failure
      volumes:
        - vol_pg:/var/lib/postgresql/data
      networks:
        - net_trans
      env_file:
        - .env

volumes:

    vol_django:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ~/data/vol_django
    vol_pg:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ~/data/vol_pg

networks:
  net_trans:
    driver: bridge
