services:

    redis:
      image: redis:6-alpine
      container_name: redis
      networks:
        - net_trans

    nginx:
      build:
        context: ./requirements/nginx/.
      container_name: nginx
      ports:
        - "1100:1100"
      restart: on-failure
      depends_on:
        - django
      volumes:
        - ./requirements/django/webapp/:/django/
        - ./requirements/django/webapp/staticfiles/:/django/staticfiles
        - ./requirements/django/webapp/media/:/django/media
      networks:
        - net_trans

    django:
      build:
        context: ./requirements/django/.
      container_name: django
      expose:
        - "8000"
      restart: on-failure
      depends_on:
        - postgres
      volumes:
        - ./requirements/django/webapp/:/django/
        - ./requirements/django/webapp/staticfiles/:/django/staticfiles
        - ./requirements/django/webapp/media/:/django/media
        - ./LOGGER/:/tmp/
      networks:
        - net_trans
      env_file:
        - .env

    postgres:
      image: postgres:latest
      container_name: postgres
      ports:
        - "5432:5432"
      restart: on-failure
      volumes:
        - vol_pg:/var/lib/postgresql/data
      networks:
        - net_trans
      env_file:
        - .env

volumes:

    vol_pg:
    vol_es:
    vol_backup:

networks:
  net_trans:
    driver: bridge
