# Generated by Django 5.1.4 on 2024-12-29 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
