# Generated by Django 5.1.4 on 2024-12-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_room_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('PVP', 'pvp'), ('TNM', 'tournament')], default='PVP', max_length=3),
        ),
    ]
