# Generated by Django 5.1.4 on 2025-01-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='started',
        ),
    ]
