# Generated by Django 5.1.3 on 2024-11-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_email_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
